### ISSUE TITLE
Content is not refreshed when slides are changed.

### ISSUE THREAD

**Issue by keithj2780** [Valexr/svelte-slidy#1]
I'd expect the slides to change reactively when when I update slidy.slides.
See REPL for example https://svelte.dev/repl/e3449b1e20e04a0da240c9e7bd9cc455?version=3.24.1

**Comment by Valexr** [comment]
Thnx for feedback. I'll think about how implement this functional in next update. But now you can use dinamicly props & change slides outside config component.

Sorry for long answer, I have pure net now...

**Comment by Valexr** [comment]
Today in new release implement this behavior by default 👍🏼

**Comment by Valexr** [comment]
@keithj2780 test please
