### ISSUE TITLE
autoplay and prev/next when click on image?

### ISSUE THREAD

**Issue by oratoran** [Valexr/svelte-slidy#13]
Thanks for awesome slider. 

I just wonder how to

1)  implement autoplay by seconds
2)  in 3 grid display; left|center|right images/captions, when click on images on the left/right how can move slide image to center (as like pressing arrows). For destop users

Thanks

**Comment by Valexr** [comment]
Tx for feedback ✌🏻 I’m not sure what you minded:
1. You need manage autoplay by timing?
2. You need change index/active slide by clicking on slides thumbs from left/right position like arrow ?

**Comment by oratoran** [comment]
1) Yes :)
2) thanks

**Comment by Valexr** [comment]
Example: https://svelte.dev/repl/5979bd8521324a9b82a584521fbca6f9?version=3.31.2

**Comment by Valexr** [comment]
@oratoran that's all? I closed it, but if you have some questions - welcome!
Tx for feedback 🤓
