### ISSUE TITLE
Use with Sapper?

### ISSUE THREAD

**Issue by Amerlander** [Valexr/svelte-slidy#15]
I try to use Slidy with Sapper.

Importing with ` import Slidy from 'svelte-slidy'` gives `'default' is not exported by node_modules\svelte-slidy\src\index.js` Error.

Changing it to `import * as Slidy from 'svelte-slidy'` says `<Slidy> is not a valid SSR component. ` .

Disabling SSR with 
```svelte
{#if (process.browser) }
<Slidy …/>
{/if}
```
results in 
`Uncaught (in promise) TypeError: Slidy is not a constructor`.

Any suggestions on this? I gave up for now.

**Comment by Valexr** [comment]
Named export now - import { Slidy } from

**Comment by Valexr** [comment]
That's all? I close it, but if you have other questions welcome!
Tx for feedback 🤓
