### ISSUE TITLE
Unable to make slider start from first slide in loop mode

### ISSUE THREAD

**Issue by tehnolog** [Valexr/svelte-slidy#16]
`index` option seems to be buggy in loop mode (`loop: true`).

Slider always appear with "middle" slide active.

`index` option only affects numbers in default pagination (`dots`) but not the slides. Slides order in array != numbers in pagination.

Take a look. Replace `index` with any value (e.g. 0) and look at the image src of active slide. It's always "...?random=5".

https://svelte.dev/repl/63eabf4de9ef40108da038cf55cba8dd?version=3.37.0

When loop mode is disabled everything works fine.

**Comment by Valexr** [comment]
it's just reload effect on bundling in REPL...  on real site `index` work fine see [this](https://slidy.valexr.online)
just set `loop: true` & open left sidebar controls (red play button 🤓) & slide  upper  input range

**Comment by Valexr** [comment]
Ok, I'm found bug. While fix it soon& Tx @tehnolog 🤓

**Comment by Valexr** [comment]
Fixed in 2.6.8
Now in `loop: true` mode you need this settings (reactive declaration prop `index` after `slidyinit === true` state):

````svelte
<script>
  let name = index, slidyinit = false
  $: slidyinit && (index = 5)
</script>

<Slidy bind:index bind:slidyinit />
````

[Example](https://svelte.dev/repl/63eabf4de9ef40108da038cf55cba8dd)

**Comment by hk7math** [comment]
This issue seems resurrected? Slidy behaves differently upon external indexing for loop of different values T T

**Comment by Valexr** [comment]
Can you explain little bit more? 
Maybe you have repl example?

**Comment by hk7math** [comment]
A bit rush now, just to add some more info and hope to provide more details later:
I am using "svelte-slidy": "^2.7.1"  and made a Slidy of 45 slides
When loop is false, setting index = 1 externally works fine.
When loop is changed to true, setting index = 1 will go to slide 19
It looks similar, if not the same, to what was described in this issue @@

**Comment by Valexr** [comment]
Look this [Example](https://svelte.dev/repl/63eabf4de9ef40108da038cf55cba8dd)
