### ISSUE TITLE
How can I implement autoplay?

### ISSUE THREAD

**Issue by brud** [Valexr/svelte-slidy#20]
Hi @Valexr, thanks for awesome slider!

I have a question: as I can see for now Slidy don't support autoplay feature. How can I implement it?

**Comment by brud** [comment]
I understand: just need to bind index and increment it :)

**Comment by Valexr** [comment]
Sorry, just received notification🤓
Yep, you are right - [example](https://svelte.dev/repl/c3f50a4277384ebf860fcb1bb8d26dae)
Docs in progress ;)

**Comment by Valexr** [comment]
& custom thumbs nav [example](https://svelte.dev/repl/5979bd8521324a9b82a584521fbca6f9)
