### ISSUE TITLE
Weird corner cases

### ISSUE THREAD

**Issue by Taha-Firoz** [Valexr/svelte-slidy#25]
When I provide the component with a regular array of urls, not objects with indexes I naively assumed it would just use the index number as an id explained in the `keyExtractor` documentation. However it doesn't work like that.

Also when urls have weird parameters like, `...%20(5)_conv.png` the component fails to render these images. I don't know why exactly since if I click on the url it does open in a separate tab, and the url does render when it's a `src` for an image tag.

Any advice on these two problems would be greatly appreciated.
and this isn't part of the issue but if you could tell me how to detect a click on an image, I'll be able to add a modal preview of image for a larger preview. 

Great library though, it works pretty well with svelte-kit in dev mode, haven't tried it in a build yet!

**Comment by Valexr** [comment]
Please give me example in svelte-repl with yours details

**Comment by Valexr** [comment]
@Taha-Firoz if you haven't questions I'm close this issue... ?!

**Comment by Taha-Firoz** [comment]
I'm going to get back today, sorry for the delay

**Comment by Valexr** [comment]
Ok, will wait your testing🤓

**Comment by Taha-Firoz** [comment]
[Heres an example](https://svelte.dev/repl/6253760be8194ad3974a1ba6fa1ff3e8?version=3.38.2) , I've added the url that I'm trying to access but it's failing to load. I can solve this issue by renaming the actual file name, but I'd like it if it worked directly. 

I'm checking the modal example you've given for a solution to opening a full screen image.
Also I solved the url listing problem by just mapping each image result.

**Comment by Taha-Firoz** [comment]
Also I've copy pasted your [example here](https://svelte.dev/repl/c4b8e256b4eb45a9be8487a891799076?version=3.38.2) into a svelte kit project and I keep getting an error. It's an exact replica of that repl
![image](https://user-images.githubusercontent.com/42237761/121685725-bba81180-cad9-11eb-9735-a4e42460ef97.png)

**Comment by Taha-Firoz** [comment]
Okay sorry, I pulled the latest version and all the issues are resolved!

**Comment by Valexr** [comment]
Tx for feedback @Taha-Firoz 👍🏻
Any other questions?

**Comment by Taha-Firoz** [comment]
I just need to custom style the dots and I can't really figure it out, I did inject my own dot via a slot but I cant capture when it's active. any way to change the active class color?

**Comment by Valexr** [comment]
```css
:global(.slidy-dots li.active) { yours: style}
```

**Comment by Taha-Firoz** [comment]
`:global(.slidy-dots li.active) { yours: style}`
This isn't working

**Comment by Taha-Firoz** [comment]
`:global(.slidy-dots li.active button) {  background: #4E6398 !important;}` I got it to work with this

**Comment by Valexr** [comment]
> `:global(.slidy-dots li.active button) { background: #4E6398 !important;}` I got it to work with this

Yep - for default element in slot 👌🏻
