### ISSUE TITLE
How to show one at a time item as in the example website

### ISSUE THREAD

**Issue by henaff** [Valexr/svelte-slidy#27]
Hi,

I'm not able to reproduce the same case as in the example website with only one item shown by the slider.
When i put two items, they are sliced and next to others and there is no more animations.
![image](https://user-images.githubusercontent.com/54863020/124576862-04d75100-de4d-11eb-976e-b1553945ceaf.png)

``` javascript
{
    slides: products,
    "wrap": {
      id: 'slidy',
      width: '100%',
      height: '100%',
      padding: '0',
      align: 'middle',
      alignmargin: 0
    },
    "slide": {
      class: 'slide',
      width: '100%',
      height: '100%',
      backimg: false,
      imgsrckey: 'picture',
      objectfit: 'cover',
      overflow: 'hidden',
    },
    controls: {
      dots: true,
      dotsnum: true,
      dotsarrow: false,
      dotspure: true,
      arrows: true,
      keys: true,
      drag: true,
      wheel: true,
    },
    options: {
      axis: 'x',
      loop: true,
      duration: 550,
      sensity: 0.3,
      "intersecting": false
    }
  }

```

``` javascript
<Slidy
    { ...slidy_cards }
    let:item
>
    <div class="slide">
        <ProductSliderItem
            product={ item }
        >
        </ProductSliderItem>
    </div>
</Slidy>
```

I tried to edit wrap.align, slide.with, slide.objectfit, slide.overflow and the mistic options.intersecting, but the result is always the same.
I also tried to lazy-load the library because i use sapper but that doesn't fix that

**Comment by henaff** [comment]
It works if i drag a little bit the slider, but still issue on page loading

**Comment by henaff** [comment]
Ok if i had a fake loading time it is fixed

**Comment by Valexr** [comment]
I can't reproduce yours bug, but in [repl](https://ru.svelte.dev/repl/1ac00a7d69c4409ebb499e614d61133c?version=3.38.3) work ok...
`intersecting` not implemented yet... it's props of intersectionObserver for logic when slide in viewport... lazy... e.t.c

**Comment by henaff** [comment]
it is maybe for sapper

**Comment by Valexr** [comment]
Slidy have `timeout: 0` props by default — it's time interval in ms before rendering slides... maybe it will be useful for you...
