### ISSUE TITLE
Can't install svelte-slidy through yarn

### ISSUE THREAD

**Issue by khc033** [Valexr/svelte-slidy#28]
When I try to install svelte-slidy through yarn, I get the following error:
error https://registry.yarnpkg.com/svelte-slidy/-/svelte-slidy-2.7.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open 'C:\\Users\\Username\\AppData\\Local\\Yarn\\Cache\\v6\\npm-svelte-slidy-2.7.1-7cd8cac2d1b16a2f4298d37f2dc3bd5d6d0354f8-integrity\\node_modules\\svelte-slidy\\Icon\r'".
Is there a way to fix this?

**Comment by Valexr** [comment]
I'm haven't Windows system for testing your error...
But on unix-like system command `yarn add -D svelte-slidy` works good🤷🏻‍♂️
