### ISSUE TITLE
order of slide is shifted by 1 when using in `loop`

### ISSUE THREAD

**Issue by Salman2301** [Valexr/svelte-slidy#30]
I use this repl to demo it
https://svelte.dev/repl/f8373ec1fbd54294b3fd6402fa925ee5?version=3.42.6

The bug is auto fixed when using the mouse wheel
But at the start, the **second slide** is in place of **first** 
So, the whole slide is shifted by 1. Slide 2 is in Slide 1, Slide 3 is in Slide 2 and Slide1 is in 3rd.
Note this happen when the `loop` is set to `true`

Please check the repl for more info

**Comment by Valexr** [comment]
Duplicate of #16 
Look this [Example](https://svelte.dev/repl/63eabf4de9ef40108da038cf55cba8dd)

**Comment by Salman2301** [comment]
I simplified it a bit
https://svelte.dev/repl/6e6d49c429cf40f89ab64951b79aa5ca?version=3.43.0

So basically, we wait for the init to be true and set the index to 0

I would hope slidy already do this for me.
OR If there is `onInit` or `onReady` event, that will be better
AND add it in the FAQ or document somewhere

Thanks for the answer

**Comment by Valexr** [comment]
Yep🤓readme not fully useful… haven’t time now for docs, but soon…👌🏻
Tx😉
