### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Pho3nixHun** [Valexr/svelte-slidy#9]
https://github.com/Valexr/svelte-slidy/blob/ab34807178800bc6ae6bcbfacaf728bd0bdce403/src/Slidy.svelte#L139

This two line has a typo. It should have be 
```js
        wrapwidth = e.detail.cR.width
        wrapheight = e.detail.cR.height
```

**Comment by Valexr** [comment]
Why? Form resizeobserver.is I have this:

`node.dispatchEvent(new CustomEvent('resize', {
            detail: { CR, ET }
        })); `

**Comment by Pho3nixHun** [comment]
I did not dig into this, but I just got an error saying  ```CR does not exist on detail```, then I checked and it was ```cR``` instead of ```CR```.
I don't know the version, but it was the one on npm by that time I posted. (I just rolled back to my fork right away)

**Comment by Valexr** [comment]
I see. Now it’s ok👌🏻Thnx for feedback👍🏻
